const WORKFLOW_IDS = {
  // Populate these IDs in src/workflow-ids.local.js (gitignored).
  USER_EMAIL: '',
  COMPANY_PREREQUISITES: '',
  CWM_CONFIGURATIONS: '',
  COMPUTER_ONLINE: '',
  COMPUTER_PREREQUISITES: '',
  MACHINE_CERT_REMEDIATION_APPLY: '019ddac0-808c-7ae4-9454-ae6488f6c089',
  OPEN_TICKET: ''
};

window.WORKFLOW_IDS = WORKFLOW_IDS;
